---
# tasks file for prod
- name: install tomcat
  apt: name=tomcat9 state=present

- name: copy artifact to prod
  synchronize: 
    src: "10.70.70.27{{readyapp_folder}}" 
    dest: "{{ work_folder }}"
    mode: pull 
    delegate_to: 10.70.70.28