---
# tasks file for prod
- name: install tomcat
  apt: name=tomcat9 state=present

- name: send artifact
  synchronize:
    hosts: 
      src: /tmp/
      dest: /var/lib/tomcat9/webapps/
  delegate_to: localhost

