---
version: '3.8'
services:
  
  run:
    image: tomcat
    ports:
      - "8080:8080"
    depends_on:
      - bld
      - database
    volumes:
      - type: volume
        source: readyapp
        target: /usr/local/tomcat/webapps/  
     
  bld:
    build:   
      context: build/
    volumes:
      - type: volume
        source: readyapp
        target: /makeapp

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: db_app
    ports:
        - "3306:3306"

volumes:
  readyapp:
networks:
  default: