---
- name: install maven
  hosts: bld
  become: yes

  tasks:
  - name: Ensure maven package is present
    apt:
      name: maven
      state: present

  - name: Clone a github repository
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /tmp/
      clone: yes
      update: yes
  - name: Build app
    command:
      chdir: /tmp/boxfuse-sample-java-war-hello/
      cmd: mvn package -Dmaven.test.skip -T 1C