---
- name: Ensure rsync package is present
  hosts: all
  become: yes
  tasks:
  
  - name: Ensure rsync package is present
    apt:
      name: rsync
      state: present

- name: Install maven
  hosts: bld
  become: yes

  tasks:
  - name: Ensure maven package is present
    apt:
      name: maven
      state: present

  - name: Clone a github repository
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /tmp/homework/
      clone: yes
      update: yes

  - name: Build application
    command:
      chdir: /tmp/homework/
      cmd: mvn package -Dmaven.test.skip -T 1C

- name: Install tomcat && pull artifact
  hosts: run
  
  tasks:
  - name: Ensure tomcat package is present
    apt:
      name: tomcat9
      state: present
      
  - name: Synchronization using rsync protocol
    synchronize:
      mode: pull
      compress: yes
      src: rsync://10.70.70.27/tmp/homework/target/
      dest: /var/lib/tomcat9/webapps/