---
- name: Install maven
  hosts: bld
  become: yes

  tasks:
  - name: Ensure maven package is present
    apt:
      name: maven
      state: present

  - name: Clone a github repository
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /tmp/homework/
      clone: yes
      update: yes

  - name: Build app
    command:
      chdir: /tmp/homework/boxfuse-sample-java-war-hello/
      cmd: mvn package -Dmaven.test.skip -T 1C

  - name: Copy app to app server
    command:
      chdir: /tmp/homework/boxfuse-sample-java-war-hello/target/
      cmd: rsync -avz hello-1.0.war root@10.70.70.28:/tmp

- name: Install tomcat
  hosts: app
  become: yes

  tasks:
  - name: Ensure tomcat package is present
    apt:
      name: tomcat9
      state: present
  
  - name: Copy app to tomcat app folder
    copy:
      src: /tmp/hello-1.0.war
      dest: /var/lib/tomcat9/webapps/