---
version: '3.8'
services:
  run:
    build:
      context: run/
    ports:
      - "8080:8080"
    networks:
      - in1
    depends_on:
      - bld
    volumes:
      - type: volume
        source: readyapp
        target: /usr/local/tomcat/webapps/  
  bld:
    build:   
      context: build/
    networks:
      - in1
    volumes:
      - type: volume
        source: readyapp
        target: /makeapp
volumes:
  readyapp:
