---
version: '3.8'
services:
  run:
    build:
      context: run/
    ports:
      - "8080:8080"
    depends_on:
      - bld
    networks:
      main:
        aliases:
          - run
    volumes:
      - type: volume
        source: readyapp
        target: /usr/local/tomcat/webapps/  
  bld:
    build:   
      context: build/
    links:
        - run
    networks:
      main:
        aliases:
          - bld
    volumes:
      - type: volume
        source: readyapp
        target: /makeapp
       
volumes:
  readyapp:
