---
version: '3.8'

services:
  bld:
    build:   
      context: build/
    links:
        - run
    volumes:
      - type: volume
        source: readyapp
        target: /makeapp
       
  run:
    build:
      context: run/
    ports:
      - "8080:8080"
    depends_on:
      - bld
    volumes:
      - type: volume
        source: readyapp
        target: /usr/local/tomcat/webapps/
    
          
volumes:
  readyapp:
