---
version: '3.8'
services:
  run:
    build:
      context: run/
    ports:
      - "8080:8080"
    links:
      - bld
    depends_on:
      - bld
    volumes:
      - type: volume
        source: readyapp
        target: /usr/local/tomcat/webapps/  
  bld:
    build:   
      context: build/
    volumes:
      - type: volume
        source: readyapp
        target: /makeapp
       
volumes:
  readyapp:
