---
version: '3.8'
services:
  run:
    build:
      image: tomcat:9.0.20-jre8-alpine
    ports:
      - "8080:8080"
    depends_on:
      - bld
    volumes:
      - type: volume
        source: readyapp
        target: /usr/local/tomcat/webapps/  
  bld:
    build:   
      context: build/
    volumes:
      - type: volume
        source: readyapp
        target: /makeapp
volumes:
  readyapp:
networks:
  default: