---
version: '3.8'
services:
  run:
    image: tomcat:9.0.20-jre8-alpine
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./boxfuse-sample-java-war-hello/target/
        target: /usr/local/tomcat/webapps/  
