---
- name: install nginx
  hosts: web
  become: yes

  tasks:
  - name: Ensure nginx package is present
    apt:
      name: nginx
      state: present

  - name: Ensure index.html present
    copy:
      src: index.html
      dest: /var/www/html

  - name: Ensure nging servise is started
    service:
      name: nginx
      state: started

  - name: Ensure SELinux is set to enforcing mode
    ansible.builtin.lineinfile:
      path: /etc/selinux/config
      regexp: '^This is the title of the webpage!'
      line: <p><script> document.write(new Date().toLocaleDateString()); </script></p>